apiVersion: v1
kind: Pod
metadata:
  annotations:
    openshift.io/scc: privileged
  name: master-0-bench
spec:
  containers:
  - command:
    - /bin/fio
    args:
    - --name=randwrite 
    - --iodepth=1 -
    - --rw=randwrite 
    - --bs=4m 
    - --size=256M
    image: quay.io/gbsalinetti/perf-utils:latest
    imagePullPolicy: IfNotPresent
    name: perf-utils-00
    resources: {}
    securityContext:
      privileged: true
      runAsUser: 0
    stdin: true
    stdinOnce: true
    tty: true
    volumeMounts:
    - mountPath: /host
      name: host
  hostNetwork: true
  hostPID: true
  nodeName: master-0
  priority: 0
  restartPolicy: Never
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - hostPath:
      path: /
      type: Directory
    name: host

